### ISSUE TITLE
Docker image architecture

### ISSUE THREAD

**Issue by dylarm** [rohitkumbhar/surmai#19]
I see that you have automatically created the Docker image in #5 (and thank you so much for that and this entire project), however it seems to only be set up for amd64. When I run the command on my arm64 device:

  ```bash
# docker compose up
[+] Running 1/0
 ⠋ Container surmai_server                                                                                          [+] Running 2/2                             Creating0.1s 
 ✔ Container surmai_server                                                                                                                                      Created0.1s 
 ! surmai_server The requested image\'s platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
Attaching to surmai_server
surmai_server  | exec /pb/init.sh: exec format error
surmai_server exited with code 0
```
This is my docker-compose.yaml:
```yaml
volumes:
  surmai_data:

services:
  surmai_server:
    container_name: surmai_server
    image: ghcr.io/rohitkumbhar/surmai:main
    volumes:
      - surmai_data:/pb_data
    ports:
      - "9090:8080"
    restart: unless-stopped
    environment:
      SURMAI_ADMIN_EMAIL: #########
      SURMAI_ADMIN_PASSWORD: #########
      PB_DATA_DIRECTORY: /pb_data
```

I know that it worked when I built the image locally, so it seems like this discussion may be of some use: https://github.com/docker/buildx/discussions/1928
